// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QT1_WEB.Models;

#nullable disable

namespace QT1_WEB.Migrations
{
    [DbContext(typeof(Qt1NetTechContext))]
    [Migration("20231020120555_UpdatedIdentityUser")]
    partial class UpdatedIdentityUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QT1_WEB.Models.Customer", b =>
                {
                    b.Property<string>("CustId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CustID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustId")
                        .HasName("PK__Customer__049E3A89A1C5839A");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("QT1_WEB.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemId")
                        .HasName("PK__Item__727E83EB14398243");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("QT1_WEB.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("CustId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CustID");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("date");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BAF52D174FD");

                    b.HasIndex("CustId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("QT1_WEB.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("UnitAmount")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC2739975B23");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("QT1_WEB.Models.Order", b =>
                {
                    b.HasOne("QT1_WEB.Models.Customer", "Cust")
                        .WithMany("Orders")
                        .HasForeignKey("CustId")
                        .HasConstraintName("FK__Order__CustID__3B75D760");

                    b.Navigation("Cust");
                });

            modelBuilder.Entity("QT1_WEB.Models.OrderDetail", b =>
                {
                    b.HasOne("QT1_WEB.Models.Item", "Item")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__OrderDeta__ItemI__3F466844");

                    b.HasOne("QT1_WEB.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__Order__3E52440B");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QT1_WEB.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QT1_WEB.Models.Item", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("QT1_WEB.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
